import { createServerClient } from "@/lib/supabase-server";
import "./globals.css";
import SupabaseProvider from "./supabase-provider";

// do not cache this layout
export const revalidate = 0;

export const metadata = {
  title: "Magic Link + Otp Flow",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerClient();

  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <html lang="en">
      <body>
        <SupabaseProvider session={session}>{children}</SupabaseProvider>
      </body>
    </html>
  );
}
